package images

import (
	"os"
	"testing"
)

func TestBuild(t *testing.T) {

	w, _ := os.Create("test.png")

	BuildImage(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 1, w)
}

func TestRaw(t *testing.T) {

	w, _ := os.Create("test2.png")

	BuildImageRaw(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 1, w)
}

func TestBmp(t *testing.T) {

	w, _ := os.Create("test3.bmp")

	BuildImageBmp(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 1, w)

}

type noopWriter struct {
}

func (*noopWriter) Write(b []byte) (int, error) {
	return len(b), nil
}

func BenchmarkBuild(b *testing.B) {
	for i := 0; i < b.N; i++ {
		BuildImage(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 100, &noopWriter{})
	}
}

func BenchmarkRaw(b *testing.B) {
	for i := 0; i < b.N; i++ {
		BuildImageRaw(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 100, &noopWriter{})
	}
}

func BenchmarkBmp(b *testing.B) {
	for i := 0; i < b.N; i++ {
		BuildImageBmp(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 100, &noopWriter{})
	}
}
