package images

import (
	"os"
	"testing"
)

func TestBuild(t *testing.T) {

	w, _ := os.Create("test.png")

	BuildImage(13, 13, "EMNORLFIKEQRGAOKLJMNQRQRGALEHBDPAMNODAFJDPIEAMLJBEMIIHRQPTTTPCHNEMNFPTTGTTABOFDBCMTGGGTDERDPHIQTTKTTEQJGJEOCDTOTDFKMJKCLRPQIQPMLGDMRJMFEIJGDAHPEFLBABACBHLRQKLBAPRQEIFEKI", 11, w)
}
