// generated by stringer -type=TokenType; DO NOT EDIT

package micropiet

import "fmt"

const _TokenType_name = "TT_WHITESPACETT_COMMENTTT_INTEGERTT_POPTT_ADDTT_SUBTT_DIVTT_MULTT_MODTT_NOTTT_GTTT_DUPTT_ROLLTT_INPUTTT_INPUT_NUMTT_OUTPUTTT_OUTPUT_NUMTT_JMPTT_PRINTTT_BRANCHTT_SWITCHTT_IDENTIFIERTT_COLONTT_HASHTT_LCURLTT_RCURLTT_STRINGTT_EOF"

var _TokenType_index = [...]uint8{13, 23, 33, 39, 45, 51, 57, 63, 69, 75, 80, 86, 93, 101, 113, 122, 135, 141, 149, 158, 167, 180, 188, 195, 203, 211, 220, 226}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	hi := _TokenType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _TokenType_index[i-1]
	}
	return _TokenType_name[lo:hi]
}
